version: "3.1"

services:
  app:
    container_name: apc-frontend-dev
    build:
      context: .
      dockerfile: Dockerfile.develop
    ports:
      - "3000:3000"
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
      - /opt/app/.next
